name: Check main branch

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**', 'tests/**']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm test

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '24.x'
          cache: pnpm
      - run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Check Build
        run: pnpm build
