name: Publish to JSR

on:
  workflow_dispatch:
  push:
    tags: '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to JSR
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          pnpm install -C scripts/versions
          pnpm install -C scripts/radashi-db

          ./scripts/versions/node_modules/.bin/tsx ./scripts/versions/ci-publish-jsr.ts
